language: scala

jdk: openjdk8

sudo: false

env:
  matrix:
    - SBT_VERSION="0.13.18"
    - SBT_VERSION="1.3.12"

script:
  - sbt "^^${SBT_VERSION}" test scripted

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
