name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Build and test
    strategy:
      matrix:
        sbt: [ '1', '2' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Cache sbt
      uses: actions/cache@v4
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier/cache/v1
          ~/.cache/coursier/v1
          ~/AppData/Local/Coursier/Cache/v1
          ~/Library/Caches/Coursier/v1
        key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

    - name: Verify formatting
      run: sbt scalafmtCheckAll

    - name: Run tests sbt 1.x
      if: ${{ matrix.sbt == 1 }}
      run: sbt test scripted

    - name: Run tests sbt 2.x
      if: ${{ matrix.sbt == 2 }}
      run: sbt ++3.3.4 test scripted
