name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Build and test for sbt-${{matrix.sbt}}
    strategy:
      matrix:
        sbt: [ '1', '2' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: sbt

    - name: Set up SBT
      uses: sbt/setup-sbt@v1

    - name: Verify formatting
      run: sbt scalafmtCheckAll

    - name: Run tests sbt 1.x
      if: ${{ matrix.sbt == 1 }}
      run: sbt test scripted

    - name: Run tests sbt 2.x
      if: ${{ matrix.sbt == 2 }}
      run: sbt ++3.7.2 test scripted

  publish:
    name: Publish artifacts
    needs: [build]
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: sbt

    - name: Set up SBT
      uses: sbt/setup-sbt@v1

    - name: Publish snapshot
      if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
      run: sbt --client +publish
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USER }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

    - name: Publish release
      if: startsWith(github.ref, 'refs/tags/v')
      run: sbt --client +publishSigned sonatypeBundleRelease
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USER }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
