name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Build and test
    strategy:
      matrix:
        sbt: [ '1', '2' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: sbt

    - name: Set up SBT
      uses: sbt/setup-sbt@v1

    - name: Verify formatting
      run: sbt scalafmtCheckAll

    - name: Run tests sbt 1.x
      if: ${{ matrix.sbt == 1 }}
      run: sbt test scripted

    - name: Run tests sbt 2.x
      if: ${{ matrix.sbt == 2 }}
      run: sbt ++3.3.4 test scripted
